apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: blue-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-deployment
  template:
    metadata:
      labels:
        app: blue-deployment
    spec:
      containers:
        - name: blue
          image: isafronenko/capstone:blue
          ports:
            - containerPort: 8080