apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    name: currency-converter
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: green-deployment
  type: LoadBalancer